language: java
script: "gradle build"
jdk:
  - oraclejdk8
  - oraclejdk7
install: gradle assemble --stacktrace

before_script:
  - echo "adding CUDA repository"
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_6.5-14_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1204_6.5-14_amd64.deb
  - sudo apt-get update -q
  - sudo apt-get install cuda
